# fucking hell, I hate localization!
# I want to kms!!!

import datetime
import sys

discord_url = "https://discord.gg/vMjXzuKqs5"
version = "Beta 0.805"
build_date = "2106"
python_ver = f"{sys.version_info.major}.{sys.version_info.minor}"
launched_lp = datetime.datetime.now().strftime('%Y-%m-%d')

localizationTable = {
    "en": {
        "title_lp_tab0": "Launch",
        "title_lp_tab1": "User Configuration",
        "title_lp_tab2": "Launcher Settings",
        "title_lp_tab3": "Avatar",
        "title_lp_tab4": "About LegacyPlay",
        "subtext_avatar_tab": "To use multiple avatar items, separate hat IDs using a semi-colon.",
        "subtext_about_tab": "LegacyPlay Launcher Application\n\n",
        "footer_about_tab": "© 2025 LegacyPlay Development Team\n\nWe do not own the client binaries, all credits go to the Roblox Corporation.",
        "cookie_dialog_title": "Action Required",
        "cookie_change_title": "Change Roblox Cookie",
        "cookie_dialog_title2": "Roblox Cookie is required",
        "cookie_change_title2": "Change your Roblox Cookie",
        "cookie_retrieve_failed": "Failed to retrieve the cookie automatically, please get one yourself from https://www.roblox.com/.",
        "cookie_retrieve_success": "Successfully retrieved cookie! You may continue now by pressing the \"Save Cookie\" button.",
        "cookie_invalid": "This is not a valid .ROBLOSECURITY cookie!",
        "cookie_empty": "Cookie cannot be empty!",
        "cookie_required": "LegacyPlay requires a Roblox cookie to function properly.\n\nThe application will now exit.",
        "server_ip_label": "Server IP:",
        "server_port_label": "Server Port:",
        "client_version_label": "Client:",
        "username_label": "Username:",
        "user_id_label": "User ID:",
        "place_file_label": "Place File:",
        "hat_ids_label": "Hat IDs:",
        "shirt_id_label": "Shirt ID:",
        "pants_id_label": "Pants ID:",
        "dark_mode_label": "Dark Mode",
        "language_label": "Language:",
        "place_label_default": "No place file selected",
        "link_label": "If assets don't work, <a href=\"#change_cookie\" style=\"text-decoration: underline; color: #007acc;\">click here</a> to change the cookie.<br>",
        "link_label2": "Join our <a href=\"#discord_server\" style=\"text-decoration: underline; color: #007acc;\">Discord community server</a> to stay updated!",
        "select_place_button": "Select Place File",
        "play_button": "Start Playing",
        "host_button": "Host Server",
        "retrieve_cookie_button": "Retrieve it",
        "save_cookie_button": "Save Cookie",
        "exit_button": "Exit",
        "success": "Success",
        "failed": "Failed",
        "invalid_input_label": "Invalid Input",
        "understood_button": "Understood",
        "missing_file_error": "Please select a place file to host.",
        "invalid_port_error": "Please specify a valid port number.",
        "invalid_ip_error": "Please enter a valid server address.",
        "cannot_join_error": "Cannot join when you are already ingame. Please try closing and try again.",
        "general_recommendation": "Please check your settings and try again.",
        "randomPhrases": [
            "Welcome to LegacyPlay!",
            "LegacyPlay creators hope you will enjoy it.",
            "Reviving classic ROBLOX experience",
            "Preserving retro clients since early 2025",
            f"Version: {version} | Build Date {build_date}",
            "Open-Source. Local. Retro.",
            "Powered by Python with the help of Qt 6/PySide6",
            f"You've launched LegacyPlay on {launched_lp}",
            "The official LegacyPlay Build",
            "Thank you for playing LegacyPlay 💙",
            "Go to the About tab to change your cookie!",
            "LegacyPlay was created on 01/01/2025.",
            "LegacyPlay wishes you a great gameplay!",
            "LegacyPlay has 2010L - 2014L.",
            "LegacyPlay was created by VMsLover on Discord.",
            f"Join our Discord! {discord_url}"
        ],
        "about_content": [
            f"Version: {version} | Build Date {build_date}",
            f"Compiled using Python {python_ver}",
            "Graphics Framework used: Qt 6/PySide6"
        ],
        "cookie_info": "LegacyPlay requires your .ROBLOSECURITY cookie for Roblox APIs authentication. This will be stored locally and only used for assets downloading.",
        "cookie_change_info": "You can change your .ROBLOSECURITY cookie below. This will be stored locally and only used for assets downloading.",
        "cookie_placeholder": "Paste your .ROBLOSECURITY cookie here..."
    },
    "ru": {
        "title_lp_tab0": "Запуск",
        "title_lp_tab1": "Настройки пользователя",
        "title_lp_tab2": "Настройки лаунчера",
        "title_lp_tab3": "Аватар",
        "title_lp_tab4": "О LegacyPlay",
        "subtext_avatar_tab": "Для использования нескольких предметов аватара разделяйте ID шляп точкой с запятой.",
        "subtext_about_tab": "Лаунчер LegacyPlay\n\n",
        "footer_about_tab": "© 2025 Команда разработчиков LegacyPlay\n\nМы не владеем бинарными файлами клиентов, все права принадлежат Roblox Corporation.",
        "cookie_dialog_title": "Требуется действие",
        "cookie_change_title": "Изменить куки Roblox",
        "cookie_dialog_title2": "Необходим куки Roblox",
        "cookie_change_title2": "Измените свой куки Roblox",
        "cookie_retrieve_failed": "Не удалось автоматически получить куки. Пожалуйста, получите его самостоятельно на https://www.roblox.com/.",
        "cookie_retrieve_success": "Куки успешно получен! Вы можете продолжить, нажав кнопку \"Сохранить куки\".",
        "cookie_invalid": "Это не действительный куки .ROBLOSECURITY!",
        "cookie_empty": "Куки не может быть пустым!",
        "cookie_required": "LegacyPlay требует куки Roblox для работы.\n\nПриложение будет закрыто.",
        "server_ip_label": "IP сервера:",
        "server_port_label": "Порт сервера:",
        "client_version_label": "Клиент:",
        "username_label": "Имя игрока:",
        "user_id_label": "ID игрока:",
        "place_file_label": "Файл плэйса:",
        "hat_ids_label": "ID шляп:",
        "shirt_id_label": "ID рубашки:",
        "pants_id_label": "ID штанов:",
        "dark_mode_label": "Тёмная тема",
        "language_label": "Язык:",
        "place_label_default": "Не был выбран файл плэйса",
        "link_label": "Если ассеты не работают, <a href=\"#change_cookie\" style=\"text-decoration: underline; color: #007acc;\">нажмите здесь</a> чтобы изменить куки.<br>",
        "link_label2": "Присоединяйтесь к нашему <a href=\"#discord_server\" style=\"text-decoration: underline; color: #007acc;\">серверу Discord</a> чтобы оставаться в курсе новостей!",
        "select_place_button": "Выбрать файл плэйса",
        "play_button": "Начать игру",
        "host_button": "Запустить сервер",
        "retrieve_cookie_button": "Получить его",
        "save_cookie_button": "Сохранить куки",
        "exit_button": "Выход",
        "success": "Успех",
        "failed": "Провал", # реально провал, полный!
        "invalid_input_label": "Неверные данные",
        "understood_button": "Понятно",
        "missing_file_error": "Пожалуйста, выберите файл плэйса для запуска сервера.",
        "invalid_port_error": "Пожалуйста, укажите действительный номер порта.",
        "invalid_ip_error": "Пожалуйста, введите действительный адрес сервера.",
        "cannot_join_error": "Нельзя присоединиться, пока вы уже в игре. Закройте клиент и попробуйте снова.",
        "general_recommendation": "Пожалуйста, проверьте свои настройки и попробуйте снова.",
        "randomPhrases": [
            "Добро пожаловать в LegacyPlay!",
            "Создатели LegacyPlay надеются, что вам понравится.",
            "Возрождаем классический опыт ROBLOX",
            "Сохраняем ретро-клиенты с начала 2025",
            f"Версия: {version} | Дата сборки {build_date}",
            "Открытый исходный код. Локальный. Ретро.",
            "Работает на Python с использованием Qt 6/PySide6",
            f"Вы запустили LegacyPlay {launched_lp}",
            "Официальная сборка LegacyPlay",
            "Спасибо, что играете в LegacyPlay 💙",
            "Перейдите на вкладку \"О программе\", чтобы изменить куки!",
            "LegacyPlay был создан 01/01/2025.",
            "LegacyPlay желает вам отличной игры!",
            "LegacyPlay поддерживает клиенты 2010L - 2014L.",
            "LegacyPlay создан VMsLover в Discord.",
            f"Присоединяйтесь к нашему Discord! {discord_url}"
        ],
        "about_content": [
            f"Версия: {version} | Дата сборки {build_date}",
            f"Скомпилировано с использованием Python {python_ver}",
            "Графический фреймворк: Qt 6/PySide6"
        ],
        "cookie_info": "LegacyPlay требует ваш куки .ROBLOSECURITY для аутентификации в API Roblox. Он будет сохранён локально и использоваться только для загрузки ассетов.",
        "cookie_change_info": "Вы можете изменить ваш куки .ROBLOSECURITY ниже. Он будет сохранён локально и использоваться только для загрузки ассетов.",
        "cookie_placeholder": "Вставьте ваш куки .ROBLOSECURITY здесь..."
    },
    "es": {
        "title_lp_tab0": "Iniciar",
        "title_lp_tab1": "Configuración",
        "title_lp_tab2": "Ajustes",
        "title_lp_tab3": "Avatar",
        "title_lp_tab4": "Acerca de",
        "subtext_avatar_tab": "Separa IDs de sombreros con punto y coma para múltiples items.",
        "subtext_about_tab": "Aplicación LegacyPlay\n\n",
        "footer_about_tab": "© 2025 Equipo LegacyPlay\n\nNo poseemos los binarios, créditos a Roblox Corporation.",
        "cookie_dialog_title": "Acción Requerida",
        "cookie_change_title": "Cambiar Cookie",
        "cookie_dialog_title2": "Cookie Requerida",
        "cookie_change_title2": "Cambie su Cookie",
        "cookie_retrieve_failed": "Error obteniendo cookie automática. Obténgala manualmente en https://www.roblox.com/",
        "cookie_retrieve_success": "¡Cookie obtenida! Presione \"Guardar Cookie\" para continuar.",
        "cookie_invalid": "¡Cookie .ROBLOSECURITY inválida!",
        "cookie_empty": "¡Cookie no puede estar vacía!",
        "cookie_required": "LegacyPlay requiere cookie de Roblox.\n\nLa aplicación se cerrará.",
        "server_ip_label": "IP Servidor:",
        "server_port_label": "Puerto:",
        "client_version_label": "Cliente:",
        "username_label": "Usuario:",
        "user_id_label": "ID Usuario:",
        "place_file_label": "Archivo Place:",
        "hat_ids_label": "IDs Sombreros:",
        "shirt_id_label": "ID Camisa:",
        "pants_id_label": "ID Pantalón:",
        "dark_mode_label": "Modo Oscuro",
        "language_label": "Idioma:",
        "place_label_default": "No seleccionado",
        "link_label": "Si assets fallan, <a href=\"#change_cookie\" style=\"text-decoration: underline; color: #007acc;\">cambie cookie aquí</a>.<br>",
        "link_label2": "Únase a nuestro <a href=\"#discord_server\" style=\"text-decoration: underline; color: #007acc;\">servidor Discord</a> para actualizaciones.",
        "select_place_button": "Seleccionar Archivo",
        "play_button": "Jugar",
        "host_button": "Hostear",
        "retrieve_cookie_button": "Obtener",
        "save_cookie_button": "Guardar Cookie",
        "exit_button": "Salir",
        "success": "Éxito",
        "failed": "Falló",
        "invalid_input_label": "Entrada Inválida",
        "understood_button": "Entendido",
        "missing_file_error": "Seleccione archivo para hostear.",
        "invalid_port_error": "Puerto inválido.",
        "invalid_ip_error": "Dirección IP inválida.",
        "cannot_join_error": "No puede unirse estando en juego. Cierre el cliente.",
        "general_recommendation": "Revise configuración e intente nuevamente.",
        "randomPhrases": [
            "¡Bienvenido a LegacyPlay!",
            "¡Disfrute LegacyPlay!",
            "Reviviendo ROBLOX clásico",
            "Preservando clientes retro desde 2025",
            f"Versión: {version} | Compilación {build_date}",
            "Open-Source. Local. Retro.",
            "Desarrollado con Python/Qt 6",
            f"Iniciado el {launched_lp}",
            "Build oficial LegacyPlay",
            "Gracias por usar LegacyPlay 💙",
            "¡Cambie su cookie en 'Acerca de'!",
            "LegacyPlay creado el 01/01/2025.",
            "¡LegacyPlay le desea buen juego!",
            "LegacyPlay soporta 2010L-2014L",
            "Creado por VMsLover (Discord)",
            f"Discord: {discord_url}"
        ],
        "about_content": [
            f"Versión: {version} | Build {build_date}",
            f"Python {python_ver}",
            "Qt 6/PySide6"
        ],
        "cookie_info": "LegacyPlay requiere su cookie .ROBLOSECURITY para autenticación. Se almacena localmente solo para descargas.",
        "cookie_change_info": "Cambie su cookie .ROBLOSECURITY abajo. Se almacena localmente solo para descargas.",
        "cookie_placeholder": "Pegue su cookie .ROBLOSECURITY aquí..."
    },
    "de": {
        "title_lp_tab0": "Starten",
        "title_lp_tab1": "Benutzerdaten",
        "title_lp_tab2": "Einstellungen",
        "title_lp_tab3": "Avatar",
        "title_lp_tab4": "Info",
        "subtext_avatar_tab": "Trennen Sie Hut-IDs mit Semikolon für mehrere Items.",
        "subtext_about_tab": "LegacyPlay Launcher\n\n",
        "footer_about_tab": "© 2025 LegacyPlay Team\n\nClient-Binärdateien gehören Roblox Corporation.",
        "cookie_dialog_title": "Aktion benötigt",
        "cookie_change_title": "Cookie ändern",
        "cookie_dialog_title2": "Roblox-Cookie benötigt",
        "cookie_change_title2": "Cookie ändern",
        "cookie_retrieve_failed": "Automatischer Abruf fehlgeschlagen. Holen Sie ihn manuell von https://www.roblox.com/",
        "cookie_retrieve_success": "Cookie erfolgreich abgerufen! Klicken Sie \"Cookie speichern\".",
        "cookie_invalid": "Ungültiger .ROBLOSECURITY-Cookie!",
        "cookie_empty": "Cookie darf nicht leer sein!",
        "cookie_required": "LegacyPlay benötigt Roblox-Cookie.\n\nWird beendet.",
        "server_ip_label": "Server-IP:",
        "server_port_label": "Port:",
        "client_version_label": "Client:",
        "username_label": "Benutzername:",
        "user_id_label": "Benutzer-ID:",
        "place_file_label": "Place-Datei:",
        "hat_ids_label": "Hut-IDs:",
        "shirt_id_label": "Shirt-ID:",
        "pants_id_label": "Hosen-ID:",
        "dark_mode_label": "Dunkelmodus",
        "language_label": "Sprache:",
        "place_label_default": "Keine Datei",
        "link_label": "Bei Asset-Problemen <a href=\"#change_cookie\" style=\"text-decoration: underline; color: #007acc;\">Cookie hier ändern</a>.<br>",
        "link_label2": "Treten Sie unserem <a href=\"#discord_server\" style=\"text-decoration: underline; color: #007acc;\">Discord-Server</a> bei!",
        "select_place_button": "Datei wählen",
        "play_button": "Spielen",
        "host_button": "Hosten",
        "retrieve_cookie_button": "Abrufen",
        "save_cookie_button": "Cookie speichern",
        "exit_button": "Beenden",
        "success": "Erfolg",
        "failed": "Fehler",
        "invalid_input_label": "Ungültig",
        "understood_button": "Verstanden",
        "missing_file_error": "Place-Datei zum Hosten wählen.",
        "invalid_port_error": "Ungültiger Port.",
        "invalid_ip_error": "Ungültige Serveradresse.",
        "cannot_join_error": "Beitreten im Spiel nicht möglich. Client schließen.",
        "general_recommendation": "Einstellungen prüfen und erneut versuchen.",
        "randomPhrases": [
            "Willkommen bei LegacyPlay!",
            "Viel Spaß mit LegacyPlay!",
            "Klassisches ROBLOX-Erlebnis",
            "Bewahrt Retro-Clients seit 2025",
            f"Version: {version} | Build {build_date}",
            "Open-Source. Lokal. Retro.",
            "Powered by Python/Qt 6",
            f"Gestartet am {launched_lp}",
            "Offizieller LegacyPlay-Build",
            "Danke fürs Nutzen 💙",
            "Cookie unter 'Info' ändern!",
            "LegacyPlay erstellt am 01/01/2025.",
            "Gutes Spielen wünscht LegacyPlay!",
            "Unterstützt 2010L-2014L",
            "Erstellt von VMsLover",
            f"Discord: {discord_url}"
        ],
        "about_content": [
            f"Version: {version} | Build {build_date}",
            f"Python {python_ver}",
            "Qt 6/PySide6"
        ],
        "cookie_info": "LegacyPlay benötigt .ROBLOSECURITY-Cookie für Authentifizierung. Wird lokal nur für Downloads gespeichert.",
        "cookie_change_info": "Ändern Sie Ihren Cookie unten. Wird lokal nur für Downloads gespeichert.",
        "cookie_placeholder": ".ROBLOSECURITY-Cookie hier einfügen..."
    },
    "pt_BR": {
        "title_lp_tab0": "Iniciar",
        "title_lp_tab1": "Configurações",
        "title_lp_tab2": "Ajustes",
        "title_lp_tab3": "Avatar",
        "title_lp_tab4": "Sobre",
        "subtext_avatar_tab": "Separe IDs de chapéus com ponto e vírgula para múltiplos itens.",
        "subtext_about_tab": "Aplicativo LegacyPlay\n\n",
        "footer_about_tab": "© 2025 Equipe LegacyPlay\n\nBinários são propriedade da Roblox Corporation.",
        "cookie_dialog_title": "Ação Necessária",
        "cookie_change_title": "Alterar Cookie",
        "cookie_dialog_title2": "Cookie Necessário",
        "cookie_change_title2": "Alterar Cookie",
        "cookie_retrieve_failed": "Falha ao obter cookie automaticamente. Obtenha manualmente em https://www.roblox.com/",
        "cookie_retrieve_success": "Cookie obtido! Clique em \"Salvar Cookie\" para continuar.",
        "cookie_invalid": "Cookie .ROBLOSECURITY inválido!",
        "cookie_empty": "Cookie não pode ser vazio!",
        "cookie_required": "LegacyPlay requer cookie Roblox.\n\nO aplicativo será fechado.",
        "server_ip_label": "IP Servidor:",
        "server_port_label": "Porta:",
        "client_version_label": "Cliente:",
        "username_label": "Usuário:",
        "user_id_label": "ID Usuário:",
        "place_file_label": "Arquivo Place:",
        "hat_ids_label": "IDs Chapéus:",
        "shirt_id_label": "ID Camisa:",
        "pants_id_label": "ID Calça:",
        "dark_mode_label": "Modo Escuro",
        "language_label": "Idioma:",
        "place_label_default": "Nenhum arquivo",
        "link_label": "Se assets falharem, <a href=\"#change_cookie\" style=\"text-decoration: underline; color: #007acc;\">altere cookie aqui</a>.<br>",
        "link_label2": "Junte-se ao nosso <a href=\"#discord_server\" style=\"text-decoration: underline; color: #007acc;\">servidor Discord</a>!",
        "select_place_button": "Selecionar Arquivo",
        "play_button": "Jogar",
        "host_button": "Hospedar",
        "retrieve_cookie_button": "Obter",
        "save_cookie_button": "Salvar Cookie",
        "exit_button": "Sair",
        "success": "Sucesso",
        "failed": "Falha",
        "invalid_input_label": "Inválido",
        "understood_button": "Entendido",
        "missing_file_error": "Selecione um arquivo para hospedar.",
        "invalid_port_error": "Porta inválida.",
        "invalid_ip_error": "Endereço inválido.",
        "cannot_join_error": "Não pode entrar estando no jogo. Feche o cliente.",
        "general_recommendation": "Verifique configurações e tente novamente.",
        "randomPhrases": [
            "Bem-vindo ao LegacyPlay!",
            "Aproveite o LegacyPlay!",
            "Revivendo ROBLOX clássico",
            "Preservando clients retro desde 2025",
            f"Versão: {version} | Build {build_date}",
            "Open-Source. Local. Retro.",
            "Desenvolvido com Python/Qt 6",
            f"Iniciado em {launched_lp}",
            "Build oficial LegacyPlay",
            "Obrigado por usar 💙",
            "Altere seu cookie em 'Sobre'!",
            "LegacyPlay criado em 01/01/2025.",
            "Bom jogo do LegacyPlay!",
            "Suporta 2010L-2014L",
            "Criado por VMsLover",
            f"Discord: {discord_url}"
        ],
        "about_content": [
            f"Versão: {version} | Build {build_date}",
            f"Python {python_ver}",
            "Qt 6/PySide6"
        ],
        "cookie_info": "LegacyPlay requer cookie .ROBLOSECURITY para autenticação. Armazenado localmente apenas para downloads.",
        "cookie_change_info": "Altere seu cookie abaixo. Armazenado localmente apenas para downloads.",
        "cookie_placeholder": "Cole seu cookie .ROBLOSECURITY aqui..."
    },
    "fr": {
        "title_lp_tab0": "Lancer",
        "title_lp_tab1": "Configuration",
        "title_lp_tab2": "Paramètres",
        "title_lp_tab3": "Avatar",
        "title_lp_tab4": "À propos",
        "subtext_avatar_tab": "Séparez les IDs de chapeaux par des points-virgules pour plusieurs items.",
        "subtext_about_tab": "Application LegacyPlay\n\n",
        "footer_about_tab": "© 2025 Équipe LegacyPlay\n\nBinaires clients propriété de Roblox Corporation.",
        "cookie_dialog_title": "Action Requise",
        "cookie_change_title": "Modifier Cookie",
        "cookie_dialog_title2": "Cookie Requis",
        "cookie_change_title2": "Modifiez votre Cookie",
        "cookie_retrieve_failed": "Échec de récupération automatique. Obtenez-le sur https://www.roblox.com/",
        "cookie_retrieve_success": "Cookie obtenu ! Cliquez \"Sauvegarder\" pour continuer.",
        "cookie_invalid": "Cookie .ROBLOSECURITY invalide !",
        "cookie_empty": "Le cookie ne peut être vide !",
        "cookie_required": "LegacyPlay nécessite un cookie Roblox.\n\nL'application va quitter.",
        "server_ip_label": "IP Serveur :",
        "server_port_label": "Port :",
        "client_version_label": "Client :",
        "username_label": "Pseudo :",
        "user_id_label": "ID Utilisateur :",
        "place_file_label": "Fichier Place :",
        "hat_ids_label": "IDs Chapeaux :",
        "shirt_id_label": "ID Chemise :",
        "pants_id_label": "ID Pantalon :",
        "dark_mode_label": "Mode Sombre",
        "language_label": "Langue :",
        "place_label_default": "Aucun fichier",
        "link_label": "Si les assets échouent, <a href=\"#change_cookie\" style=\"text-decoration: underline; color: #007acc;\">changez le cookie ici</a>.<br>",
        "link_label2": "Rejoignez notre <a href=\"#discord_server\" style=\"text-decoration: underline; color: #007acc;\">serveur Discord</a> !",
        "select_place_button": "Sélectionner Fichier",
        "play_button": "Jouer",
        "host_button": "Héberger",
        "retrieve_cookie_button": "Récupérer",
        "save_cookie_button": "Sauvegarder",
        "exit_button": "Quitter",
        "success": "Succès",
        "failed": "Échec",
        "invalid_input_label": "Invalide",
        "understood_button": "Compris",
        "missing_file_error": "Sélectionnez un fichier place.",
        "invalid_port_error": "Port invalide.",
        "invalid_ip_error": "Adresse IP invalide.",
        "cannot_join_error": "Impossible de rejoindre en jeu. Fermez le client.",
        "general_recommendation": "Vérifiez les paramètres et réessayez.",
        "randomPhrases": [
            "Bienvenue sur LegacyPlay !",
            "Profitez de LegacyPlay !",
            "ROBLOX classique relancé",
            "Préservation des clients retro depuis 2025",
            f"Version : {version} | Build {build_date}",
            "Open-Source. Local. Retro.",
            "Développé avec Python/Qt 6",
            f"Lancé le {launched_lp}",
            "Build officielle LegacyPlay",
            "Merci d'utiliser LegacyPlay 💙",
            "Changez votre cookie dans 'À propos' !",
            "LegacyPlay créé le 01/01/2025.",
            "LegacyPlay vous souhaite bon jeu !",
            "Supporte 2010L-2014L",
            "Créé par VMsLover",
            f"Discord : {discord_url}"
        ],
        "about_content": [
            f"Version : {version} | Build {build_date}",
            f"Python {python_ver}",
            "Qt 6/PySide6"
        ],
        "cookie_info": "LegacyPlay nécessite votre cookie .ROBLOSECURITY pour l'authentification. Stocké localement pour les téléchargements uniquement.",
        "cookie_change_info": "Modifiez votre cookie .ROBLOSECURITY ci-dessous. Stocké localement pour les téléchargements uniquement.",
        "cookie_placeholder": "Collez votre cookie .ROBLOSECURITY ici..."
    },
    "ja": {
        "title_lp_tab0": "起動",
        "title_lp_tab1": "ユーザー設定",
        "title_lp_tab2": "設定",
        "title_lp_tab3": "アバター",
        "title_lp_tab4": "情報",
        "subtext_avatar_tab": "複数アイテムは帽子IDをセミコロンで区切ってください。",
        "subtext_about_tab": "LegacyPlay ランチャー\n\n",
        "footer_about_tab": "© 2025 LegacyPlay チーム\n\nクライアントバイナリはRobloxの所有物です。",
        "cookie_dialog_title": "要操作",
        "cookie_change_title": "クッキー変更",
        "cookie_dialog_title2": "要Robloxクッキー",
        "cookie_change_title2": "クッキー変更",
        "cookie_retrieve_failed": "自動取得失敗。手動でhttps://www.roblox.com/から取得してください。",
        "cookie_retrieve_success": "クッキー取得成功！「保存」を押して続行。",
        "cookie_invalid": "無効な.ROBLOSECURITYクッキーです！",
        "cookie_empty": "クッキーが空です！",
        "cookie_required": "LegacyPlayにはRobloxクッキーが必要です。\n\n終了します。",
        "server_ip_label": "サーバーIP:",
        "server_port_label": "ポート:",
        "client_version_label": "クライアント:",
        "username_label": "ユーザー名:",
        "user_id_label": "ユーザーID:",
        "place_file_label": "プレースファイル:",
        "hat_ids_label": "帽子ID:",
        "shirt_id_label": "シャツID:",
        "pants_id_label": "パンツID:",
        "dark_mode_label": "ダークモード",
        "language_label": "言語:",
        "place_label_default": "未選択",
        "link_label": "アセット不具合時は<a href=\"#change_cookie\" style=\"text-decoration: underline; color: #007acc;\">クッキー変更</a>してください。<br>",
        "link_label2": "最新情報は<a href=\"#discord_server\" style=\"text-decoration: underline; color: #007acc;\">Discordサーバー</a>へ！",
        "select_place_button": "ファイル選択",
        "play_button": "プレイ",
        "host_button": "ホスト",
        "retrieve_cookie_button": "取得",
        "save_cookie_button": "保存",
        "exit_button": "終了",
        "success": "成功",
        "failed": "失敗",
        "invalid_input_label": "無効",
        "understood_button": "了解",
        "missing_file_error": "ホストするファイルを選択してください。",
        "invalid_port_error": "無効なポート。",
        "invalid_ip_error": "無効なIPアドレス。",
        "cannot_join_error": "ゲーム中は参加不可。クライアントを閉じてください。",
        "general_recommendation": "設定を確認して再試行。",
        "randomPhrases": [
            "LegacyPlayへようこそ！",
            "LegacyPlayをお楽しみください！",
            "クラシックROBLOX再現",
            "2025年よりレトロクライアント保存",
            f"バージョン: {version} | ビルド {build_date}",
            "オープンソース・ローカル・レトロ",
            "Python/Qt 6で開発",
            f"{launched_lp}起動",
            "公式LegacyPlayビルド",
            "ご利用ありがとうございます 💙",
            "クッキー変更は「情報」タブで！",
            "2025年1月1日作成",
            "良いゲーム体験を！",
            "2010L-2014L対応",
            "製作者: VMsLover",
            f"Discord: {discord_url}"
        ],
        "about_content": [
            f"バージョン: {version} | ビルド {build_date}",
            f"Python {python_ver}",
            "Qt 6/PySide6"
        ],
        "cookie_info": "LegacyPlayには.ROBLOSECURITYクッキーが必要です。アセット取得のみに使用されローカル保存されます。",
        "cookie_change_info": "下記で.ROBLOSECURITYクッキーを変更できます。アセット取得のみに使用されローカル保存されます。",
        "cookie_placeholder": ".ROBLOSECURITYクッキーを貼り付け..."
    },
    "zh_CN": {
        "title_lp_tab0": "启动",
        "title_lp_tab1": "用户配置",
        "title_lp_tab2": "启动器设置",
        "title_lp_tab3": "虚拟形象",
        "title_lp_tab4": "关于",
        "subtext_avatar_tab": "多个物品请用分号分隔帽子ID。",
        "subtext_about_tab": "LegacyPlay 启动器\n\n",
        "footer_about_tab": "© 2025 LegacyPlay 团队\n\n客户端文件版权属于Roblox公司。",
        "cookie_dialog_title": "需要操作",
        "cookie_change_title": "更改Cookie",
        "cookie_dialog_title2": "需要Roblox Cookie",
        "cookie_change_title2": "更改Cookie",
        "cookie_retrieve_failed": "自动获取失败，请从https://www.roblox.com/手动获取。",
        "cookie_retrieve_success": "Cookie获取成功！点击\"保存\"继续。",
        "cookie_invalid": "无效的.ROBLOSECURITY Cookie！",
        "cookie_empty": "Cookie不能为空！",
        "cookie_required": "LegacyPlay需要Roblox Cookie。\n\n即将退出。",
        "server_ip_label": "服务器IP:",
        "server_port_label": "端口:",
        "client_version_label": "客户端:",
        "username_label": "用户名:",
        "user_id_label": "用户ID:",
        "place_file_label": "场景文件:",
        "hat_ids_label": "帽子ID:",
        "shirt_id_label": "上衣ID:",
        "pants_id_label": "裤子ID:",
        "dark_mode_label": "暗色模式",
        "language_label": "语言:",
        "place_label_default": "未选择",
        "link_label": "资源加载失败？<a href=\"#change_cookie\" style=\"text-decoration: underline; color: #007acc;\">点击更改Cookie</a>。<br>",
        "link_label2": "加入<a href=\"#discord_server\" style=\"text-decoration: underline; color: #007acc;\">Discord社区</a>获取更新！",
        "select_place_button": "选择文件",
        "play_button": "开始游戏",
        "host_button": "开设服务器",
        "retrieve_cookie_button": "获取",
        "save_cookie_button": "保存Cookie",
        "exit_button": "退出",
        "success": "成功",
        "failed": "失败",
        "invalid_input_label": "无效输入",
        "understood_button": "明白",
        "missing_file_error": "请选择场景文件。",
        "invalid_port_error": "无效端口号。",
        "invalid_ip_error": "无效服务器地址。",
        "cannot_join_error": "游戏中无法加入。请关闭客户端重试。",
        "general_recommendation": "请检查设置后重试。",
        "randomPhrases": [
            "欢迎使用LegacyPlay！",
            "祝您使用愉快！",
            "重现经典ROBLOX体验",
            "自2025年保存复古客户端",
            f"版本: {version} | 构建 {build_date}",
            "开源 · 本地 · 复古",
            "基于Python/Qt 6开发",
            f"于{launched_lp}启动",
            "官方LegacyPlay版本",
            "感谢使用 💙",
            "在\"关于\"中更改Cookie！",
            "创建于2025年1月1日",
            "祝您游戏愉快！",
            "支持2010L-2014L版本",
            "作者: VMsLover",
            f"Discord: {discord_url}"
        ],
        "about_content": [
            f"版本: {version} | 构建 {build_date}",
            f"Python {python_ver}",
            "Qt 6/PySide6"
        ],
        "cookie_info": "LegacyPlay需要.ROBLOSECURITY Cookie进行验证。仅用于资源下载并本地存储。",
        "cookie_change_info": "您可在此更改.ROBLOSECURITY Cookie。仅用于资源下载并本地存储。",
        "cookie_placeholder": "粘贴.ROBLOSECURITY Cookie..."
    },
    "pl": {
        "title_lp_tab0": "Uruchom",
        "title_lp_tab1": "Ustawienia",
        "title_lp_tab2": "Opcje",
        "title_lp_tab3": "Awatar",
        "title_lp_tab4": "O Programie",
        "subtext_avatar_tab": "Oddziel ID czapek średnikiem dla wielu przedmiotów.",
        "subtext_about_tab": "Aplikacja LegacyPlay\n\n",
        "footer_about_tab": "© 2025 Zespół LegacyPlay\n\nPliki klienta należą do Roblox Corporation.",
        "cookie_dialog_title": "Wymagana Akcja",
        "cookie_change_title": "Zmień Ciasteczko",
        "cookie_dialog_title2": "Wymagane Ciasteczko",
        "cookie_change_title2": "Zmień Ciasteczko",
        "cookie_retrieve_failed": "Automatyczne pobieranie nieudane. Pobierz z https://www.roblox.com/",
        "cookie_retrieve_success": "Pobrano ciasteczko! Kliknij \"Zapisz\" by kontynuować.",
        "cookie_invalid": "Nieprawidłowe ciasteczko .ROBLOSECURITY!",
        "cookie_empty": "Ciasteczko nie może być puste!",
        "cookie_required": "LegacyPlay wymaga ciasteczka Roblox.\n\nAplikacja zostanie zamknięta.",
        "server_ip_label": "IP Serwera:",
        "server_port_label": "Port:",
        "client_version_label": "Klient:",
        "username_label": "Nazwa:",
        "user_id_label": "ID Użytkownika:",
        "place_file_label": "Plik Miejsca:",
        "hat_ids_label": "ID Czapek:",
        "shirt_id_label": "ID Koszuli:",
        "pants_id_label": "ID Spodni:",
        "dark_mode_label": "Tryb Ciemny",
        "language_label": "Język:",
        "place_label_default": "Nie wybrano",
        "link_label": "Problemy z zasobami? <a href=\"#change_cookie\" style=\"text-decoration: underline; color: #007acc;\">Zmień ciasteczko</a>.<br>",
        "link_label2": "Dołącz na <a href=\"#discord_server\" style=\"text-decoration: underline; color: #007acc;\">serwer Discord</a>!",
        "select_place_button": "Wybierz Plik",
        "play_button": "Graj",
        "host_button": "Hostuj",
        "retrieve_cookie_button": "Pobierz",
        "save_cookie_button": "Zapisz",
        "exit_button": "Wyjdź",
        "success": "Sukces",
        "failed": "Błąd",
        "invalid_input_label": "Nieprawidłowe",
        "understood_button": "Rozumiem",
        "missing_file_error": "Wybierz plik miejsca.",
        "invalid_port_error": "Nieprawidłowy port.",
        "invalid_ip_error": "Nieprawidłowy adres.",
        "cannot_join_error": "Nie można dołączyć w trakcie gry. Zamknij klienta.",
        "general_recommendation": "Sprawdź ustawienia i spróbuj ponownie.",
        "randomPhrases": [
            "Witaj w LegacyPlay!",
            "Miłego korzystania!",
            "Ożywiamy klasycznego ROBLOX-a",
            "Zachowujemy retro klienty od 2025",
            f"Wersja: {version} | Kompilacja {build_date}",
            "Open-Source. Lokalnie. Retro.",
            "Działa na Python/Qt 6",
            f"Uruchomiono {launched_lp}",
            "Oficjalna wersja LegacyPlay",
            "Dzięki za używanie 💙",
            "Zmień ciasteczko w 'O Programie'!",
            "LegacyPlay stworzony 01/01/2025.",
            "Życzymy miłej gry!",
            "Obsługuje 2010L-2014L",
            "Stworzone przez VMsLover",
            f"Discord: {discord_url}"
        ],
        "about_content": [
            f"Wersja: {version} | Kompilacja {build_date}",
            f"Python {python_ver}",
            "Qt 6/PySide6"
        ],
        "cookie_info": "LegacyPlay wymaga ciasteczka .ROBLOSECURITY do uwierzytelniania. Przechowywane lokalnie tylko do pobierania zasobów.",
        "cookie_change_info": "Zmień ciasteczko .ROBLOSECURITY poniżej. Przechowywane lokalnie tylko do pobierania zasobów.",
        "cookie_placeholder": "Wklej ciasteczko .ROBLOSECURITY..."
    }
}