# fucking hell, I hate localization!
# I want to kms!!!

import datetime
import sys

discord_url = "https://discord.gg/vMjXzuKqs5"
version = "Beta 0.864"
build_date = "0408"
python_ver = f"{sys.version_info.major}.{sys.version_info.minor}"
launched_lp = datetime.datetime.now().strftime('%Y-%m-%d')

localizationTable = {
    "en": {
        "title_lp_tab0": "Launch",
        "title_lp_tab1": "User Configuration",
        "title_lp_tab2": "Launcher Settings",
        "title_lp_tab3": "Avatar",
        "title_lp_tab4": "About LegacyPlay",
        "subtext_avatar_tab": "To use multiple avatar items, separate hat IDs using a semi-colon.",
        "subtext_about_tab": "LegacyPlay Launcher Application\n\n",
        "footer_about_tab": "© 2025 LegacyPlay Development Team\n\nWe do not own the client binaries, all credits go to the Roblox Corporation.",
        "cookie_dialog_title": "Action Required",
        "cookie_change_title": "Change Roblox Cookie",
        "cookie_dialog_title2": "Roblox Cookie is required",
        "cookie_change_title2": "Change your Roblox Cookie",
        "cookie_retrieve_failed": "Failed to retrieve the cookie automatically, please get one yourself from https://www.roblox.com/.",
        "cookie_retrieve_success": "Successfully retrieved cookie! You may continue now by pressing the \"Save Cookie\" button.",
        "cookie_invalid": "This is not a valid .ROBLOSECURITY cookie!",
        "cookie_empty": "Cookie cannot be empty!",
        "cookie_required": "LegacyPlay requires a Roblox cookie to function properly.\n\nThe application will now exit.",
        "server_ip_label": "Server IP:",
        "server_port_label": "Server Port:",
        "client_version_label": "Client:",
        "username_label": "Username:",
        "user_id_label": "User ID:",
        "place_file_label": "Place File:",
        "hat_ids_label": "Hat IDs:",
        "shirt_id_label": "Shirt ID:",
        "pants_id_label": "Pants ID:",
        "dark_mode_label": "Dark Mode",
        "language_label": "Language:",
        "place_label_default": "No place file selected",
        "link_label": "If assets don't work, <a href=\"#change_cookie\" style=\"text-decoration: underline; color: #007acc;\">click here</a> to change the cookie.<br>",
        "link_label2": "Join our <a href=\"#discord_server\" style=\"text-decoration: underline; color: #007acc;\">Discord community server</a> to stay updated!",
        "select_place_button": "Select Place File",
        "play_button": "Start Playing",
        "host_button": "Host Server",
        "retrieve_cookie_button": "Retrieve it",
        "save_cookie_button": "Save Cookie",
        "exit_button": "Exit",
        "success": "Success",
        "failed": "Failed",
        "invalid_input_label": "Invalid Input",
        "understood_button": "Understood",
        "missing_file_error": "Please select a place file to host.",
        "invalid_port_error": "Please specify a valid port number.",
        "invalid_ip_error": "Please enter a valid server address.",
        "cannot_join_error": "Cannot join when you are already ingame. Please try closing and try again.",
        "general_recommendation": "Please check your settings and try again.",
        "randomPhrases": [
            "Welcome to LegacyPlay!",
            "LegacyPlay creators hope you will enjoy it.",
            "Reviving classic ROBLOX experience",
            "Preserving retro clients since early 2025",
            f"Version: {version} | Build Date {build_date}",
            "Open-Source. Local. Retro.",
            "Powered by Python with the help of Qt 6/PySide6",
            f"You've launched LegacyPlay on {launched_lp}",
            "The official LegacyPlay Build",
            "Thank you for playing LegacyPlay 💙",
            "Go to the About tab to change your cookie!",
            "LegacyPlay was created on 01/01/2025.",
            "LegacyPlay wishes you a great gameplay!",
            "LegacyPlay has 2010L - 2014L.",
            "LegacyPlay was created by VMsLover on Discord.",
            f"Join our Discord! {discord_url}"
        ],
        "about_content": [
            f"Version: {version} | Build Date {build_date}",
            f"Compiled using Python {python_ver}",
            "Graphics Framework used: Qt 6/PySide6"
        ],
        "cookie_info": "LegacyPlay requires your .ROBLOSECURITY cookie for Roblox APIs authentication. This will be stored locally and only used for assets downloading.",
        "cookie_change_info": "You can change your .ROBLOSECURITY cookie below. This will be stored locally and only used for assets downloading.",
        "cookie_placeholder": "Paste your .ROBLOSECURITY cookie here..."
    },
    "ru": {
        "title_lp_tab0": "Запуск",
        "title_lp_tab1": "Настройки пользователя",
        "title_lp_tab2": "Настройки лаунчера",
        "title_lp_tab3": "Аватар",
        "title_lp_tab4": "О LegacyPlay",
        "subtext_avatar_tab": "Для использования нескольких предметов аватара разделяйте ID шляп точкой с запятой.",
        "subtext_about_tab": "Лаунчер LegacyPlay\n\n",
        "footer_about_tab": "© 2025 Команда разработчиков LegacyPlay\n\nМы не владеем бинарными файлами клиентов, все права принадлежат Roblox Corporation.",
        "cookie_dialog_title": "Требуется действие",
        "cookie_change_title": "Изменить куки Roblox",
        "cookie_dialog_title2": "Необходим куки Roblox",
        "cookie_change_title2": "Измените свой куки Roblox",
        "cookie_retrieve_failed": "Не удалось автоматически получить куки. Пожалуйста, получите его самостоятельно на https://www.roblox.com/.",
        "cookie_retrieve_success": "Куки успешно получен! Вы можете продолжить, нажав кнопку \"Сохранить куки\".",
        "cookie_invalid": "Это не действительный куки .ROBLOSECURITY!",
        "cookie_empty": "Куки не может быть пустым!",
        "cookie_required": "LegacyPlay требует куки Roblox для работы.\n\nПриложение будет закрыто.",
        "server_ip_label": "IP сервера:",
        "server_port_label": "Порт сервера:",
        "client_version_label": "Клиент:",
        "username_label": "Имя игрока:",
        "user_id_label": "ID игрока:",
        "place_file_label": "Файл плэйса:",
        "hat_ids_label": "ID шляп:",
        "shirt_id_label": "ID рубашки:",
        "pants_id_label": "ID штанов:",
        "dark_mode_label": "Тёмная тема",
        "language_label": "Язык:",
        "place_label_default": "Не был выбран файл плэйса",
        "link_label": "Если ассеты не работают, <a href=\"#change_cookie\" style=\"text-decoration: underline; color: #007acc;\">нажмите здесь</a> чтобы изменить куки.<br>",
        "link_label2": "Присоединяйтесь к нашему <a href=\"#discord_server\" style=\"text-decoration: underline; color: #007acc;\">серверу Discord</a> чтобы оставаться в курсе новостей!",
        "select_place_button": "Выбрать файл плэйса",
        "play_button": "Начать игру",
        "host_button": "Запустить сервер",
        "retrieve_cookie_button": "Получить его",
        "save_cookie_button": "Сохранить куки",
        "exit_button": "Выход",
        "success": "Успех",
        "failed": "Провал", # реально провал, полный!
        "invalid_input_label": "Неверные данные",
        "understood_button": "Понятно",
        "missing_file_error": "Пожалуйста, выберите файл плэйса для запуска сервера.",
        "invalid_port_error": "Пожалуйста, укажите действительный номер порта.",
        "invalid_ip_error": "Пожалуйста, введите действительный адрес сервера.",
        "cannot_join_error": "Нельзя присоединиться, пока вы уже в игре. Закройте клиент и попробуйте снова.",
        "general_recommendation": "Пожалуйста, проверьте свои настройки и попробуйте снова.",
        "randomPhrases": [
            "Добро пожаловать в LegacyPlay!",
            "Создатели LegacyPlay надеются, что вам понравится.",
            "Возрождаем классический опыт ROBLOX",
            "Сохраняем ретро-клиенты с начала 2025",
            f"Версия: {version} | Дата сборки {build_date}",
            "Открытый исходный код. Локальный. Ретро.",
            "Работает на Python с использованием Qt 6/PySide6",
            f"Вы запустили LegacyPlay {launched_lp}",
            "Официальная сборка LegacyPlay",
            "Спасибо, что играете в LegacyPlay 💙",
            "Перейдите на вкладку \"О программе\", чтобы изменить куки!",
            "LegacyPlay был создан 01/01/2025.",
            "LegacyPlay желает вам отличной игры!",
            "LegacyPlay поддерживает клиенты 2010L - 2014L.",
            "LegacyPlay создан VMsLover в Discord.",
            f"Присоединяйтесь к нашему Discord! {discord_url}"
        ],
        "about_content": [
            f"Версия: {version} | Дата сборки {build_date}",
            f"Скомпилировано с использованием Python {python_ver}",
            "Графический фреймворк: Qt 6/PySide6"
        ],
        "cookie_info": "LegacyPlay требует ваш куки .ROBLOSECURITY для аутентификации в API Roblox. Он будет сохранён локально и использоваться только для загрузки ассетов.",
        "cookie_change_info": "Вы можете изменить ваш куки .ROBLOSECURITY ниже. Он будет сохранён локально и использоваться только для загрузки ассетов.",
        "cookie_placeholder": "Вставьте ваш куки .ROBLOSECURITY здесь..."
    },
    "pt_BR": {
        "title_lp_tab0": "Iniciar",
        "title_lp_tab1": "Configurações do Usuário",
        "title_lp_tab2": "Ajustes",
        "title_lp_tab3": "Avatar",
        "title_lp_tab4": "Sobre",
        "subtext_avatar_tab": "Separe IDs de chapéus com ponto e vírgula para múltiplos itens.",
        "subtext_about_tab": "Aplicativo LegacyPlay\n\n",
        "footer_about_tab": "© 2025 Equipe LegacyPlay\n\nBinários são propriedade da Roblox Corporation.",
        "cookie_dialog_title": "Ação Necessária",
        "cookie_change_title": "Alterar Cookie",
        "cookie_dialog_title2": "Cookie Necessário",
        "cookie_change_title2": "Alterar Cookie",
        "cookie_retrieve_failed": "Falha ao obter cookie automaticamente. Obtenha manualmente em https://www.roblox.com/",
        "cookie_retrieve_success": "Cookie obtido! Clique em \"Salvar Cookie\" para continuar.",
        "cookie_invalid": "Cookie .ROBLOSECURITY inválido!",
        "cookie_empty": "Cookie não pode ser vazio!",
        "cookie_required": "LegacyPlay requer cookie Roblox.\n\nO aplicativo será fechado.",
        "server_ip_label": "IP Do Servidor:",
        "server_port_label": "Porta:",
        "client_version_label": "Versão:",
        "username_label": "Nome Do Usuário:",
        "user_id_label": "ID De Usuário:",
        "place_file_label": "Arquivo RBXL:",
        "hat_ids_label": "IDs De Acessorios:",
        "shirt_id_label": "ID Da Camisa:",
        "pants_id_label": "ID Da Calça:",
        "dark_mode_label": "Modo Escuro",
        "language_label": "Idioma:",
        "place_label_default": "Nenhum arquivo selecionado",
        "link_label": "Se assets falharem, <a href=\"#change_cookie\" style=\"text-decoration: underline; color: #007acc;\">altere seu cookie aqui</a>.<br>",
        "link_label2": "Junte-se ao nosso <a href=\"#discord_server\" style=\"text-decoration: underline; color: #007acc;\">servidor do Discord</a>!",
        "select_place_button": "Selecionar Arquivo",
        "play_button": "Jogar",
        "host_button": "Hospedar",
        "retrieve_cookie_button": "Obter",
        "save_cookie_button": "Salvar Cookie",
        "exit_button": "Sair",
        "success": "Sucesso",
        "failed": "Falha",
        "invalid_input_label": "Inválido",
        "understood_button": "Entendido",
        "missing_file_error": "Selecione um arquivo para hospedar.",
        "invalid_port_error": "Porta inválida.",
        "invalid_ip_error": "Endereço inválido.",
        "cannot_join_error": "Não pode entrar estando dentro de um jogo. Feche o jogo aberto.",
        "general_recommendation": "Verifique as configurações e tente novamente.",
        "randomPhrases": [
            "Bem-vindo ao LegacyPlay!",
            "Aproveite o LegacyPlay!",
            "Revivendo ROBLOX clássico",
            "Preservando versões retro desde 2025",
            f"Versão: {version} | Build {build_date}",
            "Open-Source. Local. Retro.",
            "Desenvolvido com Python/Qt 6",
            f"Você iniciou LegacyPlay em {launched_lp}",
            "Build oficial LegacyPlay",
            "Obrigado por jogar LegacyPlay 💙",
            "Altere seu cookie em 'Sobre'!",
            "LegacyPlay criado em 01/01/2025.",
            "LegacyPlay lhe deseja uma ótima gameplay!",
            "Suporta 2010L-2014L",
            "Criado por VMsLover",
            f"Discord: {discord_url}"
        ],
        "about_content": [
            f"Versão: {version} | Build {build_date}",
            f"Python {python_ver}",
            "Qt 6/PySide6"
        ],
        "cookie_info": "LegacyPlay requer um cookie .ROBLOSECURITY para autenticação. Armazenado localmente apenas para downloads.",
        "cookie_change_info": "Altere seu cookie abaixo. Armazenado localmente apenas para downloads.",
        "cookie_placeholder": "Cole seu cookie .ROBLOSECURITY aqui..."
    },
    "tr": {
        "title_lp_tab0": "Başlat",
        "title_lp_tab1": "Kullanıcı Yapılandırması",
        "title_lp_tab2": "Uygulama Ayarları",
        "title_lp_tab3": "Karakter",
        "title_lp_tab4": "LegacyPlay Hakkında",
        "subtext_avatar_tab": "Birden fazla aksesuar giymek için, şapka ID'lerini virgül ile ayır.",
        "subtext_about_tab": "LegacyPlay Launcher Uygulaması\n\n",
        "footer_about_tab": "© 2025 LegacyPlay Geliştirici Ekip\n\nClient binary'leri bizim değildir, bütün krediler Roblox Corp'una gitmektedir.",
        "cookie_dialog_title": "Müdahale Gerek",
        "cookie_change_title": "Roblox Cookie'sini değiştir",
        "cookie_dialog_title2": "Roblox Cookie'si gerekmektedir",
        "cookie_change_title2": "Roblox Cookie'ni değiştir",
        "cookie_retrieve_failed": "Otomatik cookie'yi alma başarasız oldu, lütfen bu siteden cookie'ni geri al: https://www.roblox.com/.",
        "cookie_retrieve_success": "Cookie başarıyla geri getirildi! \"Save Cookie\" butonuna basarak devam edebilirsin.",
        "cookie_invalid": "Bu doğru bir .ROBLOSECURITY cookie'si değil!",
        "cookie_empty": "Cookie boş olamaz!",
        "cookie_required": "LegacyPlay düzgün çalışabilmesi için bir Roblox cookie'si lazım. \n\nUygulamadan çıkış yapılıyor.",
        "server_ip_label": "Sunucu IP:",
        "server_port_label": "Sunucu Port:",
        "client_version_label": "Client:",
        "username_label": "Kullanıcı Adı:",
        "user_id_label": "Kullanıcı ID:",
        "place_file_label": "Yer Dosyası:",
        "hat_ids_label": "Şapka IDleri:",
        "shirt_id_label": "Tişört IDsi:",
        "pants_id_label": "Pantolon IDsi:",
        "dark_mode_label": "Karanlık Mod",
        "language_label": "Dil:",
        "place_label_default": "Yer dosyası seçilmedi",
        "link_label": "Eğer asset'ler çalışmıyorsa, <a href=\"#change_cookie\" style=\"text-decoration: underline; color: #007acc;\">buraya tıkla</a> cookie'ni değiştirmek için <br>",
        "link_label2": "Güncel kalmak için <a href=\"#discord_server\" style=\"text-decoration: underline; color: #007acc;\">Discord sunucumuza</a> katılın!",
        "select_place_button": "Yer Dosyası Seç",
        "play_button": "Oynamaya başla",
        "host_button": "Sunucu Host'la",
        "retrieve_cookie_button": "Geri Getir",
        "save_cookie_button": "Cookie'ni kaydet",
        "exit_button": "Çık",
        "success": "Başarılı",
        "failed": "Başarısız",
        "invalid_input_label": "Yanlış giriş",
        "understood_button": "Anlaşıldı",
        "missing_file_error": "Lütfen Host'lamak için yer dosyası seç.",
        "invalid_port_error": "Lütfen doğru bir Port numarası yazınız.",
        "invalid_ip_error": "Lütfen doğru bir Sunucu adresi yazınız.",
        "cannot_join_error": "Zaten oyundayken tekrardan katılamazsın. Lütfen kapatıp tekrar deneyin.",
        "general_recommendation": "Lütfen ayarlarınıza tekrar bakın ve tekrar deneyin.",
        "randomPhrases": [
            "LegacyPlay'e hoş geldin!",
            "LegacyPlay'in yapımcıları umuyor ki bu deneyimden tatmin kalırsınız.",
            "Klasik ROBLOX deneyimini hayata getiriyoruz",
            "2025'in başlangıcından beridir eski Client'ları muhazava etmekteyiz",
            f"Versiyon: {version} | Çıkış Tarihi {build_date}",
            "Açık-kaynak. Lokal. Retro.",
            "Python tarafından güçlendirildi, Qt 6/PySide6'nin yardımıyla.",
            f" {launched_lp} tarihinde LegacyPlay oynadın.",
            "Resmi LegacyPlay Build'ı",
            "LegacyPlay oynadığın için teşekkürler 💙",
            "Cookie'ni değiştirmek için Hakkında bölümüne git!",
            "LegacyPlay 01/01/2025'de oluşturuldu.",
            "LegacyPlay umuyor ki eğlenirsin!",
            "LegacyPlay 2010L - 2014L'e sahip.",
            "LegacyPlay, Discord üzerinde VMsLover tarafından oluşturuldu.",
            f"Discord'umuza katıl! {discord_url}"
        ],
        "about_content": [
            f"Versiyon: {version} | Çıkış Tarihi {build_date}",
            f"Python {python_ver} kullanılarak yapıldı.",
            "Kullanılan Grafik Framework: Qt 6/PySide6"
        ],
        "cookie_info": "Roblox API'ının doğrulama aşaması için LegacyPlay, .ROBLOSECURITY Cookie'ni istemektedir. Asset indirmek ve kullanmak için bu Cookie lokal olarak kaydedilecektir.",
        "cookie_change_info": "Aşağıda .ROBLOSECURITY Cookie'ni yerleştirebilirsin. Asset indirmek ve kullanmak için bu Cookie lokal olarak kaydedilecektir.",
        "cookie_placeholder": ".ROBLOSECURITY Cookie'ni buraya yapıştır..."
    },
    "ua": {
        "title_lp_tab0": "Запустити",
        "title_lp_tab1": "Конфігурація Користувача",
        "title_lp_tab2": "Налаштування Лаунчера",
        "title_lp_tab3": "Аватар",
        "title_lp_tab4": "Про LegacyPlay",
        "subtext_avatar_tab": "Щоб мати більше елементів аватара, відокремлюй айді капелюхів за допомогою семі-колон.",
        "subtext_about_tab": "Додаток LegacyPlay Лаунчер\n\n",
        "footer_about_tab": "© 2025 Комадна Розробників LegacyPlay\n\nМи не володіємо бінарними файлами клієнта, усі права належать корпорації Roblox.",
        "cookie_dialog_title": "Необхідна дія",
        "cookie_change_title": "Змінити Roblox Кукі",
        "cookie_dialog_title2": "потрібен Roblox Кукі",
        "cookie_change_title2": "Зміни свій Roblox Кукі",
        "cookie_retrieve_failed": "Ми не змогли отримати кукі автоматично, будь ласка отримай один самостійно у https://www.roblox.com/.",
        "cookie_retrieve_success": "Успішно Отримали кукі! Ви можете продовжити зараз натискаючи кнопку \"Зберегти Кукі\".",
        "cookie_invalid": "Це не вірне .ROBLOSECURITY кукі!",
        "cookie_empty": "Кукі не может бути порожнім",
        "cookie_required": "LegacyPlay потрібен Roblox кукі щоб функціювати правильно.\n\nПрограма тепер закриється.",
        "server_ip_label": "Айпі Сервера:",
        "server_port_label": "Порт Сервера:",
        "client_version_label": "Клієнт:",
        "username_label": "Ім'я Користувача:",
        "user_id_label": "Айді Користувача:",
        "place_file_label": "Файл гри:",
        "hat_ids_label": "Айді капелюхів:",
        "shirt_id_label": "Айді Футболки:",
        "pants_id_label": "Айді Штанів:",
        "dark_mode_label": "Темний Режим",
        "language_label": "Язик:",
        "place_label_default": "Файл плейсу не обраний",
        "link_label": "Якщо ресурси не роблять, <a href=\"#change_cookie\" style=\"text-decoration: underline; color: #007acc;\">натисни мене</a> щоб змінити кукі.<br>",
        "link_label2": "Заходьте у наше <a href=\"#discord_server\" style=\"text-decoration: underline; color: #007acc;\">Діскорд комьюнити</a> щоб бути в курсі подій!",
        "select_place_button": "Обрати Файл Плейсу",
        "play_button": "Почати Грати",
        "host_button": "Запустити Сервер",
        "retrieve_cookie_button": "Отримати",
        "save_cookie_button": "Зберегти Кукі",
        "exit_button": "Вийти",
        "success": "Успіх",
        "failed": "Невдало",
        "invalid_input_label": "Недійсний ввід",
        "understood_button": "Зрозумів",
        "missing_file_error": "Будь ласка обери файл плейсу щоб запустити сервер.",
        "invalid_port_error": "Будь ласка уточни що порт правильний.",
        "invalid_ip_error": "Будь ласка введи вірну адресу серверу.",
        "cannot_join_error": "Неможливо приєднатись коли ти вже у грі. Будь ласка закрийте гру а зпробуйте ще раз.",
        "general_recommendation": "Будь ласка глянь налаштування та попробуй знов.",
        "randomPhrases": [
            "Ласкаво Просимо до LegacyPlay!",
            "творці LegacyPlay надіються що тобі сподобається.",
            "Відроджуємо досвід класичного Роблоксу",
            "Зберігаємо старі клієнти ще з початку 2025 року",
            f"Версія: {version} | Дата Білду {build_date}",
            "Відкритий Ресурс. Локальний. Ретро.",
            "Працює за допомогою Пайтона з допомогою від Qt 6/PySide6",
            f"ви запустили LegacyPlay на {launched_lp}",
            "Офіційний білд LegacyPlay",
            "Дякуємо що ви граєте у LegacyPlay 💙",
            "Перейдіть до Вкладки \"Про LegacyPlay\" щоб змінити своє кукі!",
            "LegacyPlay був створений 01/01/2025.",
            "LegacyPlay бажає вам гарного геймплею!",
            "LegacyPlay має 2010L - 2014L.",
            "LegacyPlay був створений VMsLover-ом у Діскорді.",
            f"Заходь до нашого Discord! {discord_url}"
        ],
        "about_content": [
            f"Версія: {version} | Дата Білду {build_date}",
            f"Компіліровано за допомогою Python {python_ver}",
            "Графічний фреймворк: Qt 6/PySide6"
        ],
        "cookie_info": "LegacyPlay потребує ваше .ROBLOSECURITY кукі для автентифікації Roblox Апішників. Це буде зберігатися локально та використовуватися лише для завантаження ресурсів.",
        "cookie_change_info": "Ви можете змінити своє .ROBLOSECURITY кукі знизу. Це буде зберігатися локально та використовуватися лише для завантаження ресурсів.",
        "cookie_placeholder": "Встав свій .ROBLOSECURITY кукі сюди..."
    },
    "de": {
        "title_lp_tab0": "Starten",
        "title_lp_tab1": "Benutzereinstellungen",
        "title_lp_tab2": "Launcher Einstellungen",
        "title_lp_tab3": "Avatar",
        "title_lp_tab4": "Über LegacyPlay",
        "subtext_avatar_tab": "Um mehrere Avatar-Items zu benutzen, trenne die Hut-IDs mit einem Semikolon.",
        "subtext_about_tab": "LegacyPlay Launcher Applikation\n\n",
        "footer_about_tab": "© 2025 LegacyPlay Development Team\n\nWir besitzen die Client-Binärdateien nicht, alle Rechte gehen and die Roblox Corporation",
        "cookie_dialog_title": "Maßnahme erforderlich",
        "cookie_change_title": "Roblox Cookie Ändern",
        "cookie_dialog_title2": "Roblox Cookie wird benötigt",
        "cookie_change_title2": "Ändere deinen Roblox Cookie",
        "cookie_retrieve_failed": "Die Roblox Cookie konnte nicht gefunden werden, gehen sie auf https://www.roblox.com/ um ihre Roblox Cookie zu erhalten.",
        "cookie_retrieve_success": "Cookie erfolgreich abgerufen! Du kannst jetzt fortfahren und auf \"Cookie Speichern\" klicken.",
        "cookie_invalid": "Dies ist keine gültige .ROBLOSECURITY cookie!",
        "cookie_empty": "Cookie kann nicht leer sein!",
        "cookie_required": "LegacyPlay benötigt eine Roblox cookie.\n\nLegacyPlay wird jetzt beendet.",
        "server_ip_label": "Server IP:",
        "server_port_label": "Server Port:",
        "client_version_label": "Client:",
        "username_label": "Benutzername:",
        "user_id_label": "Benutzer-ID:",
        "place_file_label": "Place-Datei:",
        "hat_ids_label": "Hut-IDs:",
        "shirt_id_label": "Shirt-ID:",
        "pants_id_label": "Hosen-ID:",
        "dark_mode_label": "Dark Mode",
        "language_label": "Sprache:",
        "place_label_default": "Keine Place-Datei ausgewählt",
        "link_label": "Wenn assets nicht funktionieren, <a href=\"#change_cookie\" style=\"text-decoration: underline; color: #007acc;\">klicke hier</a> um den cookie zu ändern.<br>",
        "link_label2": "Treten sie unseren <a href=\"#discord_server\" style=\"text-decoration: underline; color: #007acc;\">Discord community server</a> um immer im neuesten stand zu sein!",
        "select_place_button": "Place-Datei auswählen",
        "play_button": "Spielen",
        "host_button": "Server Hosten",
        "retrieve_cookie_button": "Cookie Erhalten",
        "save_cookie_button": "Cookie Speichern",
        "exit_button": "Beenden",
        "success": "Erfolgreich",
        "failed": "Fehlgeschlagen",
        "invalid_input_label": "Ungültige Eingabe",
        "understood_button": "Verstanden",
        "missing_file_error": "Bitte wähle eine Place-Datei zum Hosten aus..",
        "invalid_port_error": "Bitte gebe eine gültige Portnummer an.",
        "invalid_ip_error": "Bitte gebe eine gültige Serveradresse an.",
        "cannot_join_error": "Du kannst nicht beitreten, während du bereits im Spiel bist. Beenden sie das Spiel und versuche es erneut.",
        "general_recommendation": "Bitte überprüfe deine Einestellungen und versuche es erneut",
        "randomPhrases": [
            "Willkommen bei LegacyPlay!",
            "LegacyPlay entwickler hoffen, dass es dir gefällt.",
            "Das Klassische ROBLOX erlebnis wiederbeleben",
            "Seit Anfang 2025 Retro-Clients im Fokus",
            f"Version: {version} | Erstellungsdatum {build_date}",
            "Open-Source. Local. Retro.",
            "Powered by Python with the help of Qt 6/PySide6",
            f"Du hast LegacyPlay zuletzt am {launched_lp} gespielt",
            "Der offizielle LegacyPlay Build",
            "Danke das du LegacyPlay spielst 💙",
            "Gehe zum Über-Tab, um dein Cookie zu ändern!",
            "LegacyPlay wurde am 01/01/2025 erstellt.",
            "LegacyPlay wünscht dir viel Spaß beim Spielen!",
            "LegacyPlay hat 2010L - 2014L.",
            "LegacyPlay wurde von VMsLover auf Discord erstellt.",
            f"Trete unseren Discord bei! {discord_url}"
        ],
        "about_content": [
            f"Version: {version} | Erstellungsdatum {build_date}",
            f"Kompiliert mit Python {python_ver}",
            "Benutzt Graphics Framework: Qt 6/PySide6"
        ],
        "cookie_info": "LegacyPlay benötigt deine .ROBLOSECURITY cookie für Roblox-API Authentifizierungen. Diese wird lokal gespeichert und nur verwendet um Assets herunterzuladen.",
        "cookie_change_info": "Du kannst deine .ROBLOSECURITY cookie unten ändern. Diese wird lokal gespeichert und nur verwendet um Assets herunterzuladen.",
        "cookie_placeholder": "Füge deine .ROBLOSECURITY cookie hier ein..."
    }
}